name: GitHub Action

on: 
  push:
    branches:    
      - master

jobs:
  deploy:
    name: GitHub Pipeline
    runs-on: macos-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout
        uses: actions/checkout@v2

      # Step 2: Set up Xcode version 16.2
      - name: Selecting Xcode Version
        run: sudo xcode-select -switch /Applications/Xcode_16.2.app

      # Step 3: Verify Xcode version
      - name: Verify Xcode Version
        run: /usr/bin/xcodebuild -version

      # Step 4: Install xcpretty (if not installed)
      - name: Install xcpretty
        run: sudo gem install xcpretty

      # Step 5: List available simulators to check availability
      - name: List available simulators
        run: xcrun simctl list

      # Step 6: Clean Build
      - name: Clean Build
        run: |
          xcodebuild clean -project Woloo.xcodeproj -scheme Woloo | xcpretty

      # Step 7: Build and Test with JUnit Report
      - name: Build and Test with JUnit Report
        run: |
          xcodebuild test -project Woloo.xcodeproj -scheme Woloo -destination 'platform=iOS Simulator,name=iPhone 14,OS=16.2' | xcpretty -r junit > result.xml
      
      # Step 8: Upload Test Results to GitHub
      - name: Upload Test Results to GitHub
        uses: actions/upload-artifact@v3
        with:
          name: junit-test-results
          path: result.xml
