name: GitHub Action

on: 
  push:
    branches:    
      - master

jobs:
  deploy:
    name: GitHub Pipeline
    runs-on: macos-latest
    
    steps:
      # Step 1: Checkout the repository
      - name: Checkout
        uses: actions/checkout@v2

      # Step 2: Set up Xcode version 16.2
      - name: Selecting Xcode Version
        run: sudo xcode-select -switch /Applications/Xcode_16.2.app

      # Step 3: Verify Xcode version
      - name: Verify Xcode Version
        run: /usr/bin/xcodebuild -version

      - name: List available simulators
        run: xcrun simctl list

      # Step 4: Clean the Xcode build
      - name: Clean Build
        run: |
          xcodebuild clean -project Woloo.xcodeproj -scheme Woloo | xcpretty

      # Step 5: Run JUnit tests (without simulator)
      - name: Run JUnit Tests
        run: |
          xcodebuild test -project Woloo.xcodeproj -scheme Woloo | xcpretty -s
